# Use the file to pull Mongo DB and GenieACS from DockerHub #

version: "3"
services:
# Dockerfile here: https://github.com/docker-library/mongo/blob/master/4.4/Dockerfile
    mongo:
        image: mongo:4.4
        restart: always
        container_name: "mongo"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/var/log/mongodb
        ports: 
            - "27017:27017"
        volumes:
            - data_db:/data/db
            - data_configdb:/data/configdb
        expose: 
            - 27017
        networks:
            - gnetwork

# Dockerfile here: https://github.com/topeqin/docker/genieacs. Using image from hub or build from dockerfile
    genieacs:
        depends_on:
            - 'mongo'
        image: topeqin/genieacs:1.2.0
        #build:
        #   context: ./
        #   dockerfile: Dockerfile_GenieACS
        restart: always
        container_name: "genieacs"
        environment:
            - GENIEACS_UI_JWT_SECRET=changeme
            - GENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-cwmp-access.log
            - GENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-nbi-access.log
            - GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log
            - GENIEACS_UI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-ui-access.log
            - GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml
            - GENIEACS_EXT_DIR=/opt/genieacs/ext
            - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo/genieacs
        ports:
            - "7547:7547"
            - "7557:7557"
            - "7567:7567"
            - "3000:3000"
        volumes:
            - opt_volume:/opt
        networks:
            - gnetwork

### THIS SERVICE IS JUST FOR TESTING PURPOSES ###
    genieacs-sim:
        depends_on:
            - 'genieacs'
        image: drumsergio/genieacs-sim
        container_name: "genieacs-sim"
        networks:
            - gnetwork

# Dockerfile here: https://github.com/topeqin/docker/genieacs
    dhcpd:
        image: networkboot/dhcpd
        restart: always
        container_name: "dhcpd"
        network_mode: "host"
        environment:
            - DHCPD_PROTOCOL=4
        volumes:
            - ./data:/data
        command: " enp0s3"
        #networks:
        #   host:
        #      name: host
        #      external: true

volumes:
    data_db:
    data_configdb:
    opt_volume:

networks:
    gnetwork:
